[build]
  command = "yarn build"
  publish = "build/client"
  functions = "build/server"

[dev]
  command = "yarn dev"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
